// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcf7V8pPNal0jkR8F1XQuy_GFsBttqocQ',
    appId: '1:977298458089:web:93be94362dba7871f7f778',
    messagingSenderId: '977298458089',
    projectId: 'flutter-stripe-payment-80c2c',
    authDomain: 'flutter-stripe-payment-80c2c.firebaseapp.com',
    storageBucket: 'flutter-stripe-payment-80c2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqhi__W9q9y0IAM7_G-P5IT4UO-IscpQ',
    appId: '1:977298458089:android:ba71c9d10a6567f4f7f778',
    messagingSenderId: '977298458089',
    projectId: 'flutter-stripe-payment-80c2c',
    storageBucket: 'flutter-stripe-payment-80c2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAFf_Kjs4yIFRdXpXY-MSjddecicrmmo',
    appId: '1:977298458089:ios:9e3578ba738eca42f7f778',
    messagingSenderId: '977298458089',
    projectId: 'flutter-stripe-payment-80c2c',
    storageBucket: 'flutter-stripe-payment-80c2c.appspot.com',
    iosClientId: '977298458089-hj91261saiump65nejmc8heu6r0kdqdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStripePayment',
  );
}
